import type { ComponentDoc } from "../types"
import { baseUi, classNameProp, primitiveRest, renderProp, restProp } from "./shared"

export const dataDisplay: ComponentDoc[] = [
  {
    slug: "card",
    name: "Card",
    group: "Hiển thị dữ liệu",
    runtime: "server",
    description: "Hộp nội dung với header, action, nội dung và footer. Thêm `variant` cho ba bề mặt của FrameON: thẻ thường, bảng lồng `elevated` và khối `promo` viền vàng mời nâng cấp VIP.",
    imports: 'import { Card, CardAction, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@hwagfu/frameui/card"',
    shadcn: "card",
    examples: [
      { file: "card-demo", title: "Tiếp tục xem" },
      { file: "card-variants", title: "Ba bề mặt FrameON" },
    ],
    api: [
      { name: "Card", props: [{ name: "variant", type: '"default" | "elevated" | "promo"', default: '"default"', description: "Bề mặt thẻ." }, { name: "size", type: '"default" | "sm"', default: '"default"', description: "Khoảng đệm 16px hoặc 12px (elevated/promo: 24px)." }, classNameProp, restProp("div")] },
      { name: "CardHeader · CardTitle · CardDescription · CardAction · CardContent · CardFooter", props: [classNameProp, restProp("div")] },
    ],
  },
  {
    slug: "table",
    name: "Table",
    group: "Hiển thị dữ liệu",
    runtime: "server",
    description: "Bảng dữ liệu ngữ nghĩa. Hàng rê chuột sáng bề mặt lồng, tiêu đề cột 12px màu xám.",
    imports: 'import { Table, TableBody, TableCaption, TableCell, TableFooter, TableHead, TableHeader, TableRow } from "@hwagfu/frameui/table"',
    shadcn: "table",
    examples: [{ file: "table-demo", title: "Hoá đơn" }],
    api: [{ name: "Table và các phần", props: [classNameProp, restProp("table | thead | tbody | tr | th | td")] }],
  },
  {
    slug: "data-table",
    name: "Data Table",
    group: "Hiển thị dữ liệu",
    runtime: "client",
    description:
      "Bảng có sắp xếp, lọc, phân trang, ẩn cột và chọn dòng — hướng dẫn Data Table của shadcn (TanStack Table v9) đóng gói thành `DataTable` cùng các mảnh `DataTableColumnHeader`, `DataTablePagination`, `DataTableViewOptions`.",
    imports: 'import { DataTable, DataTableColumnHeader, type DataTableFeatures } from "@hwagfu/frameui/data-table"',
    shadcn: "data-table",
    uses: ["@tanstack/react-table"],
    examples: [{ file: "data-table-demo", title: "Kho phim" }],
    api: [
      { name: "DataTable", props: [{ name: "columns", type: "ColumnDef<DataTableFeatures, TData>[]", description: "Định nghĩa cột (dùng `createColumnHelper<DataTableFeatures, TData>()`)." }, { name: "data", type: "TData[]", description: "Dữ liệu." }, { name: "filterColumn", type: "string", description: "Id cột lọc bằng ô tìm kiếm." }, { name: "filterPlaceholder", type: "string", description: "Chữ gợi ý của ô lọc." }, { name: "pageSizeOptions", type: "number[]", default: "[10, 20, 30, 50]", description: "Các lựa chọn số dòng mỗi trang." }, { name: "emptyMessage", type: "ReactNode", description: "Nội dung khi không có dòng nào." }, { name: "toolbar", type: "(table) => ReactNode", description: "Chèn thêm điều khiển vào thanh công cụ." }] },
      { name: "DataTableColumnHeader", props: [{ name: "column", type: "Column", description: "Cột hiện tại (từ header context)." }, { name: "title", type: "string", description: "Tên cột." }] },
    ],
    notes: ["`dataTableFeatures` khai báo sẵn các tính năng v9 (sort, filter, pagination, visibility, selection); chỉ tính năng được khai báo mới vào bundle."],
  },
  {
    slug: "avatar",
    name: "Avatar",
    group: "Hiển thị dữ liệu",
    runtime: "island",
    description: "Ảnh đại diện có chữ viết tắt dự phòng (chữ vàng trên nền slate), huy hiệu trạng thái và nhóm chồng nhau.",
    imports: 'import { Avatar, AvatarBadge, AvatarFallback, AvatarGroup, AvatarGroupCount, AvatarImage } from "@hwagfu/frameui/avatar"',
    primitive: baseUi("Avatar", "avatar"),
    shadcn: "avatar",
    examples: [{ file: "avatar-demo", title: "Kích thước, huy hiệu và nhóm" }],
    api: [{ name: "Avatar", props: [{ name: "size", type: '"sm" | "default" | "lg"', default: '"default"', description: "24 / 32 / 40px." }, primitiveRest("Avatar.Root")] }],
  },
  {
    slug: "item",
    name: "Item",
    group: "Hiển thị dữ liệu",
    runtime: "server",
    description: "Hàng nội dung linh hoạt: media, tiêu đề, mô tả, hành động. Khi là liên kết, rê chuột thì tiêu đề chuyển vàng.",
    imports: 'import { Item, ItemActions, ItemContent, ItemDescription, ItemGroup, ItemMedia, ItemSeparator, ItemTitle } from "@hwagfu/frameui/item"',
    shadcn: "item",
    examples: [{ file: "item-demo", title: "Tài khoản và danh sách" }],
    api: [
      { name: "Item", props: [{ name: "variant", type: '"default" | "outline" | "muted"', default: '"default"', description: "Viền hoặc nền." }, { name: "size", type: '"default" | "sm" | "xs"', default: '"default"', description: "Mật độ." }, renderProp, classNameProp] },
      { name: "ItemMedia", props: [{ name: "variant", type: '"default" | "icon" | "image"', default: '"default"', description: "`icon` = ô vuông nền slate với icon vàng." }] },
    ],
  },
  {
    slug: "empty",
    name: "Empty",
    group: "Hiển thị dữ liệu",
    runtime: "server",
    description: "Trạng thái rỗng. Mặc định là bảng `elevated` như EmptyState của FrameON; thêm `className` để thành dạng viền đứt.",
    imports: 'import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@hwagfu/frameui/empty"',
    shadcn: "empty",
    examples: [{ file: "empty-demo", title: "Không tìm thấy phim" }],
    api: [{ name: "EmptyMedia", props: [{ name: "variant", type: '"default" | "icon"', default: '"default"', description: "`icon` = ô 48px với icon vàng." }] }],
  },
  {
    slug: "chart",
    name: "Chart",
    group: "Hiển thị dữ liệu",
    runtime: "client",
    description: "Biểu đồ trên Recharts. `ChartContainer` nạp màu theo `config`, tooltip và chú thích theo phong cách FrameON. Bảng màu `--chart-1…5`: tím, vàng, xanh lá, cam, đỏ.",
    imports: 'import { ChartContainer, ChartLegend, ChartLegendContent, ChartTooltip, ChartTooltipContent, type ChartConfig } from "@hwagfu/frameui/chart"',
    shadcn: "chart",
    uses: ["recharts"],
    examples: [
      { file: "chart-demo", title: "Cột" },
      { file: "chart-area", title: "Vùng" },
    ],
    api: [
      { name: "ChartContainer", props: [{ name: "config", type: "ChartConfig", description: "Nhãn, icon và màu của từng chuỗi dữ liệu (`color` hoặc `theme: { dark, light }`)." }] },
      { name: "ChartTooltipContent", props: [{ name: "indicator", type: '"dot" | "line" | "dashed"', default: '"dot"', description: "Kiểu dấu màu." }, { name: "hideLabel / hideIndicator", type: "boolean", description: "Ẩn nhãn hoặc dấu màu." }] },
    ],
  },
  {
    slug: "carousel",
    name: "Carousel",
    group: "Hiển thị dữ liệu",
    runtime: "client",
    description: "Dải trượt ngang/dọc trên Embla — hợp cho rail poster của FrameON. Nút điều hướng tròn, mờ dần khi tới đầu/cuối.",
    imports: 'import { Carousel, CarouselContent, CarouselItem, CarouselNext, CarouselPrevious } from "@hwagfu/frameui/carousel"',
    shadcn: "carousel",
    uses: ["embla-carousel-react"],
    examples: [{ file: "carousel-demo", title: "Rail poster" }],
    api: [{ name: "Carousel", props: [{ name: "opts", type: "EmblaOptions", description: "Tuỳ chọn Embla (align, loop…)." }, { name: "plugins", type: "EmblaPlugin[]", description: "Plugin Embla (autoplay…)." }, { name: "orientation", type: '"horizontal" | "vertical"', default: '"horizontal"', description: "Hướng trượt." }, { name: "setApi", type: "(api) => void", description: "Lấy API Embla để điều khiển." }] }],
  },
  {
    slug: "accordion",
    name: "Accordion",
    group: "Hiển thị dữ liệu",
    runtime: "island",
    description: "Các mục thu gọn/mở rộng. Tiêu đề mục đang mở và khi rê chuột chuyển vàng, mũi tên xoay.",
    imports: 'import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@hwagfu/frameui/accordion"',
    primitive: baseUi("Accordion", "accordion"),
    shadcn: "accordion",
    examples: [{ file: "accordion-demo", title: "Câu hỏi thường gặp" }],
    api: [{ name: "Accordion", props: [{ name: "defaultValue / value / onValueChange", type: "string[]", description: "Các mục đang mở." }, { name: "multiple", type: "boolean", description: "Cho mở nhiều mục cùng lúc." }, primitiveRest("Accordion.Root")] }],
  },
  {
    slug: "collapsible",
    name: "Collapsible",
    group: "Hiển thị dữ liệu",
    runtime: "island",
    description: "Vùng nội dung mở/đóng có hoạt ảnh chiều cao.",
    imports: 'import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@hwagfu/frameui/collapsible"',
    primitive: baseUi("Collapsible", "collapsible"),
    shadcn: "collapsible",
    examples: [{ file: "collapsible-demo", title: "Danh sách diễn viên" }],
    api: [{ name: "Collapsible", props: [{ name: "open / defaultOpen / onOpenChange", type: "boolean", description: "Trạng thái mở." }, primitiveRest("Collapsible.Root")] }],
  },
  {
    slug: "progress",
    name: "Progress",
    group: "Hiển thị dữ liệu",
    runtime: "island",
    description: "Thanh tiến độ mảnh với phần đã chạy màu vàng — như ProgressLine trên thẻ phim FrameON.",
    imports: 'import { Progress, ProgressLabel, ProgressValue } from "@hwagfu/frameui/progress"',
    primitive: baseUi("Progress", "progress"),
    shadcn: "progress",
    examples: [{ file: "progress-demo", title: "Đã xem, đang tải, không xác định" }],
    api: [{ name: "Progress", props: [{ name: "value", type: "number | null", description: "0–100; `null` = không xác định." }, primitiveRest("Progress.Root")] }],
  },
  {
    slug: "attachment",
    name: "Attachment",
    group: "Hiển thị dữ liệu",
    runtime: "server",
    description: "Thẻ tệp đính kèm với trạng thái đang tải (chữ ánh chạy), lỗi, chờ.",
    imports: 'import { Attachment, AttachmentAction, AttachmentActions, AttachmentContent, … } from "@hwagfu/frameui/attachment"',
    shadcn: "attachment",
    examples: [{ file: "attachment-demo", title: "Tệp phụ đề và video" }],
    api: [{ name: "Attachment", props: [{ name: "state", type: '"idle" | "uploading" | "processing" | "error" | "done"', default: '"done"', description: "Trạng thái tệp." }, { name: "size", type: '"default" | "sm" | "xs"', default: '"default"', description: "Mật độ." }, { name: "orientation", type: '"horizontal" | "vertical"', default: '"horizontal"', description: "Bố cục." }] }],
  },
  {
    slug: "marker",
    name: "Marker",
    group: "Hiển thị dữ liệu",
    runtime: "server",
    description: "Dấu mốc trong dòng thời gian hoặc hội thoại: dạng thường, có đường kẻ hai bên, hoặc gạch chân.",
    imports: 'import { Marker, MarkerContent, MarkerIcon } from "@hwagfu/frameui/marker"',
    shadcn: "marker",
    examples: [{ file: "marker-demo", title: "Mốc thời gian" }],
    api: [{ name: "Marker", props: [{ name: "variant", type: '"default" | "separator" | "border"', default: '"default"', description: "Kiểu mốc." }, renderProp] }],
  },
]
