import type { ComponentDoc } from "../types"
import { baseUi, classNameProp, primitiveRest, renderProp, restProp } from "./shared"

export const feedback: ComponentDoc[] = [
  {
    slug: "alert",
    name: "Alert",
    group: "Phản hồi",
    runtime: "server",
    description: "Thông báo tĩnh trong trang. Ngoài `default` / `destructive` của shadcn có thêm `success`, `warning`, `info` theo các sắc thái Toast của FrameON.",
    imports: 'import { Alert, AlertAction, AlertDescription, AlertTitle } from "@hwagfu/frameui/alert"',
    shadcn: "alert",
    examples: [{ file: "alert-demo", title: "Các sắc thái" }],
    api: [{ name: "Alert", props: [{ name: "variant", type: '"default" | "destructive" | "success" | "warning" | "info"', default: '"default"', description: "Sắc thái — tô màu icon (và viền với destructive/warning)." }, classNameProp, restProp("div")] }],
  },
  {
    slug: "sonner",
    name: "Sonner",
    group: "Phản hồi",
    runtime: "island",
    description:
      "Toaster của FrameON được mô phỏng theo sonner, nên đây là bản thay thế trực tiếp: chồng thẻ thu gọn, rê chuột để mở, khoảng cách 14px, tự đóng sau 4 giây, icon màu theo sắc thái. Wrapper là Server Component; chỉ `<Toaster>` của sonner là client.",
    imports: 'import { Toaster } from "@hwagfu/frameui/sonner"\nimport { toast } from "sonner"',
    shadcn: "sonner",
    uses: ["sonner"],
    examples: [{ file: "sonner-demo", title: "Gọi toast() từ bất cứ đâu" }],
    api: [{ name: "Toaster", props: [{ name: "position", type: '"top-left" | … | "bottom-right"', default: '"bottom-right"', description: "Vị trí chồng thông báo." }, { name: "...props", type: "ToasterProps", description: "Toàn bộ prop của sonner." }] }],
    notes: [
      "Đặt `<Toaster />` một lần ở layout gốc (có thể là Server Component).",
      "`toast`, `toast.success`, `toast.promise`, `toast.dismiss`… lấy thẳng từ gói `sonner` — cùng API với hàm `toast()` cũ của FrameON.",
      "Không có trong barrel `@hwagfu/frameui` vì trùng tên `Toaster` với Toast của Base UI — hãy import từ `@hwagfu/frameui/sonner`.",
    ],
  },
  {
    slug: "toast",
    name: "Toast",
    group: "Phản hồi",
    runtime: "client",
    description: "Toast dựng trên Base UI (bản shadcn mới): chồng thẻ, vuốt để đóng, `toast.promise`. Cùng hình thức với Toast của FrameON.",
    imports: 'import { Toaster, toast } from "@hwagfu/frameui/toast"',
    primitive: baseUi("Toast", "toast"),
    shadcn: "toast",
    examples: [{ file: "toast-demo", title: "Toast Base UI" }],
    api: [
      { name: "toast", props: [{ name: "add(options)", type: "{ title, description, type, timeout, … }", description: "Thêm thông báo; `type`: success · info · warning · error · loading." }, { name: "promise(p, { loading, success, error })", type: "…", description: "Bám theo một promise." }, { name: "close(id)", type: "(id?: string) => void", description: "Đóng thông báo." }] },
      { name: "Toaster", props: [{ name: "toastManager", type: "ToastManager", default: "toast", description: "Bộ quản lý riêng (tạo bằng `createToastManager()`)." }, primitiveRest("Toast.Provider")] },
    ],
  },
]

export const chat: ComponentDoc[] = [
  {
    slug: "message",
    name: "Message",
    group: "Hội thoại",
    runtime: "server",
    description: "Khung một tin nhắn: avatar, tiêu đề, nội dung, chân — căn trái hoặc phải.",
    imports: 'import { Message, MessageAvatar, MessageContent, MessageFooter, MessageGroup, MessageHeader } from "@hwagfu/frameui/message"',
    shadcn: "message",
    examples: [{ file: "message-demo", title: "Phòng xem chung" }],
    api: [{ name: "Message", props: [{ name: "align", type: '"start" | "end"', default: '"start"', description: "Phía hiển thị." }, classNameProp, restProp("div")] }],
  },
  {
    slug: "bubble",
    name: "Bubble",
    group: "Hội thoại",
    runtime: "server",
    description: "Bong bóng chat với các biến thể màu FrameON (tím, vàng, bề mặt lồng…) và phản hồi cảm xúc.",
    imports: 'import { Bubble, BubbleContent, BubbleGroup, BubbleReactions } from "@hwagfu/frameui/bubble"',
    shadcn: "bubble",
    examples: [{ file: "bubble-demo", title: "Các biến thể" }],
    api: [
      { name: "Bubble", props: [{ name: "variant", type: '"default" | "golden" | "secondary" | "muted" | "tinted" | "outline" | "ghost" | "destructive"', default: '"default"', description: "Màu bong bóng." }, { name: "align", type: '"start" | "end"', default: '"start"', description: "Phía." }] },
      { name: "BubbleContent", props: [renderProp] },
      { name: "BubbleReactions", props: [{ name: "side / align", type: '"top" | "bottom" / "start" | "end"', description: "Vị trí cụm cảm xúc." }] },
    ],
  },
  {
    slug: "message-scroller",
    name: "Message Scroller",
    group: "Hội thoại",
    runtime: "client",
    description: "Khung cuộn tin nhắn tự bám đáy khi có tin mới, với nút “cuộn xuống cuối”.",
    imports: 'import { MessageScroller, MessageScrollerButton, MessageScrollerContent, MessageScrollerItem, MessageScrollerProvider, MessageScrollerViewport } from "@hwagfu/frameui/message-scroller"',
    shadcn: "message-scroller",
    uses: ["@shadcn/react"],
    examples: [{ file: "message-scroller-demo", title: "Tự cuộn khi có tin mới" }],
  },
  {
    slug: "questionnaire",
    name: "Questionnaire",
    group: "Hội thoại",
    runtime: "client",
    description: "Bảng hỏi nhiều bước, lựa chọn dạng thẻ sáng viền vàng khi chọn, phím tắt bàn phím.",
    imports: 'import { Questionnaire, QuestionnaireChoice, QuestionnaireChoices, QuestionnaireItem, … } from "@hwagfu/frameui/questionnaire"',
    shadcn: "questionnaire",
    uses: ["@shadcn/react"],
    examples: [{ file: "questionnaire-demo", title: "Gợi ý phim" }],
    api: [{ name: "QuestionnaireItem", props: [{ name: "name", type: "string", description: "Tên câu hỏi (khoá trong FormData)." }, { name: "multiple", type: "boolean", description: "Cho chọn nhiều (checkbox)." }, { name: "required", type: "boolean", description: "Bắt buộc trả lời." }] }],
  },
]

export const utilities: ComponentDoc[] = [
  {
    slug: "scroll-area",
    name: "Scroll Area",
    group: "Tiện ích",
    runtime: "island",
    description: "Vùng cuộn với thanh cuộn tự vẽ, chỉ hiện khi rê chuột hoặc đang cuộn.",
    imports: 'import { ScrollArea, ScrollBar } from "@hwagfu/frameui/scroll-area"',
    primitive: baseUi("Scroll Area", "scroll-area"),
    shadcn: "scroll-area",
    examples: [{ file: "scroll-area-demo", title: "Danh sách tập" }],
  },
  {
    slug: "resizable",
    name: "Resizable",
    group: "Tiện ích",
    runtime: "island",
    description: "Các khung kéo giãn được; đường kéo sáng vàng khi rê chuột hoặc đang kéo.",
    imports: 'import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from "@hwagfu/frameui/resizable"',
    shadcn: "resizable",
    uses: ["react-resizable-panels"],
    examples: [{ file: "resizable-demo", title: "Bố cục trình phát" }],
    api: [
      { name: "ResizablePanelGroup", props: [{ name: "orientation", type: '"horizontal" | "vertical"', description: "Hướng chia khung." }] },
      { name: "ResizablePanel", props: [{ name: "defaultSize / minSize / maxSize", type: 'number | "40%" | "200px"', description: "Kích thước khung." }] },
      { name: "ResizableHandle", props: [{ name: "withHandle", type: "boolean", description: "Hiện tay nắm." }] },
    ],
  },
  {
    slug: "direction",
    name: "Direction",
    group: "Tiện ích",
    runtime: "island",
    description: "Cung cấp hướng văn bản (LTR/RTL) cho các component Base UI bên trong.",
    imports: 'import { DirectionProvider, useDirection } from "@hwagfu/frameui/direction"',
    primitive: baseUi("Direction Provider", "direction-provider"),
    shadcn: "direction",
    examples: [{ file: "direction-demo", title: "Thanh kéo RTL" }],
  },
]
