import type { ComponentDoc } from "../types"
import { baseUi, classNameProp, primitiveRest, restProp, sideProps } from "./shared"

export const forms: ComponentDoc[] = [
  {
    slug: "input",
    name: "Input",
    group: "Biểu mẫu",
    runtime: "server",
    description:
      "Ô nhập của FrameON: cao 42px, nền trong mờ, viền xám; khi focus viền vàng kèm quầng sáng. Tất cả bằng CSS nên vẫn là Server Component và gửi được trong `<form>` trước khi JS tải xong.",
    imports: 'import { Input } from "@hwagfu/frameui/input"',
    shadcn: "input",
    examples: [
      { file: "input-demo", title: "Trạng thái", description: "`aria-invalid` cho viền vàng báo lỗi như FrameON." },
      { file: "input-field", title: "Với nhãn, gợi ý và lỗi", description: "Ghép cùng `Field` thay cho các prop label/hint/error cũ." },
    ],
    api: [{ name: "Input", props: [classNameProp, restProp("input")] }],
    notes: ["Ô nhập viên thuốc có biểu tượng (SearchBox của FrameON) → dùng `InputGroup` với `className=\"rounded-full\"`."],
  },
  {
    slug: "input-group",
    name: "Input Group",
    group: "Biểu mẫu",
    runtime: "island",
    description:
      "Ô nhập có phần phụ (icon, chữ, nút, phím tắt) hai bên hoặc trên/dưới. Quầng sáng vàng chuyển từ ô nhập ra cả nhóm. Phần duy nhất chạy ở client là một lá cực nhỏ: bấm vào phần phụ thì focus ô nhập.",
    imports:
      'import { InputGroup, InputGroupAddon, InputGroupButton, InputGroupInput, InputGroupText, InputGroupTextarea } from "@hwagfu/frameui/input-group"',
    shadcn: "input-group",
    examples: [{ file: "input-group-demo", title: "Tìm kiếm, hậu tố và textarea" }],
    api: [
      { name: "InputGroup", props: [classNameProp, restProp("div")] },
      { name: "InputGroupAddon", props: [{ name: "align", type: '"inline-start" | "inline-end" | "block-start" | "block-end"', default: '"inline-start"', description: "Vị trí phần phụ so với ô nhập." }, classNameProp] },
      { name: "InputGroupButton", props: [{ name: "size", type: '"xs" | "sm" | "icon-xs" | "icon-sm"', default: '"xs"', description: "Cỡ nút gọn cho bên trong ô nhập." }, { name: "variant", type: "ButtonVariant", default: '"ghost"', description: "Như Button." }] },
      { name: "InputGroupInput / InputGroupTextarea", props: [restProp("input | textarea")] },
    ],
  },
  {
    slug: "input-otp",
    name: "Input OTP",
    group: "Biểu mẫu",
    runtime: "client",
    description: "Nhập mã một lần theo từng ô. Ô đang nhập sáng viền vàng, con trỏ nhấp nháy màu vàng.",
    imports: 'import { InputOTP, InputOTPGroup, InputOTPSeparator, InputOTPSlot } from "@hwagfu/frameui/input-otp"',
    shadcn: "input-otp",
    uses: ["input-otp"],
    examples: [{ file: "input-otp-demo", title: "Mã 6 số" }],
    api: [
      { name: "InputOTP", props: [{ name: "maxLength", type: "number", description: "Số ký tự." }, { name: "value / onChange", type: "string / (value) => void", description: "Điều khiển giá trị." }, { name: "containerClassName", type: "string", description: "Class cho khung chứa các ô." }] },
      { name: "InputOTPSlot", props: [{ name: "index", type: "number", description: "Vị trí ký tự mà ô hiển thị." }] },
    ],
  },
  {
    slug: "textarea",
    name: "Textarea",
    group: "Biểu mẫu",
    runtime: "server",
    description: "Ô nhập nhiều dòng, cùng bề mặt với Input, tự giãn theo nội dung (`field-sizing: content`).",
    imports: 'import { Textarea } from "@hwagfu/frameui/textarea"',
    shadcn: "textarea",
    examples: [{ file: "textarea-demo", title: "Bình luận" }],
    api: [{ name: "Textarea", props: [classNameProp, restProp("textarea")] }],
  },
  {
    slug: "native-select",
    name: "Native Select",
    group: "Biểu mẫu",
    runtime: "server",
    description: "`<select>` gốc của trình duyệt khoác áo FrameON. Không cần JS, hoạt động trên mọi thiết bị; danh sách mở do hệ điều hành vẽ.",
    imports: 'import { NativeSelect, NativeSelectOptGroup, NativeSelectOption } from "@hwagfu/frameui/native-select"',
    shadcn: "native-select",
    examples: [{ file: "native-select-demo", title: "Thể loại và năm" }],
    api: [{ name: "NativeSelect", props: [{ name: "size", type: '"sm" | "default"', default: '"default"', description: "36px hoặc 42px." }, classNameProp, restProp("select")] }],
  },
  {
    slug: "select",
    name: "Select",
    group: "Biểu mẫu",
    runtime: "island",
    description:
      "Ô chọn với danh sách tự vẽ: bảng thả xuống dưới nút, dòng đang trỏ nền lồng + chữ vàng, dấu tick vàng ở lựa chọn hiện tại — y hệt Select của FrameON, nhưng bàn phím và ARIA do Base UI lo.",
    imports:
      'import { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectSeparator, SelectTrigger, SelectValue } from "@hwagfu/frameui/select"',
    primitive: baseUi("Select", "select"),
    shadcn: "select",
    examples: [{ file: "select-demo", title: "Chất lượng video", description: "Truyền `items` để `SelectValue` hiện nhãn thay cho value." }],
    api: [
      { name: "Select", props: [{ name: "items", type: "Array<{ value, label }> | Record<string, ReactNode>", description: "Bảng tra nhãn cho `SelectValue`." }, { name: "value / defaultValue / onValueChange", type: "…", description: "Điều khiển hoặc không điều khiển lựa chọn." }, primitiveRest("Select.Root")] },
      { name: "SelectTrigger", props: [{ name: "size", type: '"sm" | "default"', default: '"default"', description: "36px hoặc 42px." }, classNameProp] },
      { name: "SelectContent", props: [...sideProps, { name: "alignItemWithTrigger", type: "boolean", default: "false", description: "`true` để bảng chọn đè lên nút kiểu macOS; mặc định thả xuống như FrameON." }] },
      { name: "SelectItem", props: [{ name: "value", type: "string", description: "Giá trị của lựa chọn." }, { name: "disabled", type: "boolean", description: "Khoá lựa chọn." }] },
    ],
  },
  {
    slug: "combobox",
    name: "Combobox",
    group: "Biểu mẫu",
    runtime: "island",
    description:
      "Ô nhập kèm danh sách lọc theo chữ gõ. Chế độ chọn nhiều hiển thị giá trị thành các chip viên thuốc vàng — đúng kiểu Tag đang bật của FrameON.",
    imports: 'import { Combobox, ComboboxContent, ComboboxInput, ComboboxItem, ComboboxList, … } from "@hwagfu/frameui/combobox"',
    primitive: baseUi("Combobox", "combobox"),
    shadcn: "combobox",
    examples: [
      { file: "combobox-demo", title: "Chọn một" },
      { file: "combobox-multiple", title: "Chọn nhiều (chip)" },
    ],
    api: [
      { name: "Combobox", props: [{ name: "items", type: "readonly Item[]", description: "Danh sách để lọc." }, { name: "multiple", type: "boolean", description: "Cho chọn nhiều." }, primitiveRest("Combobox.Root")] },
      { name: "ComboboxInput", props: [{ name: "showTrigger", type: "boolean", default: "true", description: "Hiện nút mũi tên." }, { name: "showClear", type: "boolean", default: "false", description: "Hiện nút xoá." }] },
      { name: "ComboboxContent", props: [...sideProps, { name: "anchor", type: "Ref", description: "Neo bảng chọn vào phần tử khác (dùng với `useComboboxAnchor`)." }] },
      { name: "ComboboxChip", props: [{ name: "showRemove", type: "boolean", default: "true", description: "Hiện nút × trên chip." }] },
    ],
    notes: ["`ComboboxList` nhận hàm render `(item) => …` nên phần dùng nó phải nằm trong Client Component."],
  },
  {
    slug: "checkbox",
    name: "Checkbox",
    group: "Biểu mẫu",
    runtime: "island",
    description: "Ô đánh dấu 18px của FrameON: nền slate, viền xanh xám; khi chọn chuyển tím với dấu tick trắng nét đậm. Hỗ trợ trạng thái `indeterminate`.",
    imports: 'import { Checkbox } from "@hwagfu/frameui/checkbox"',
    primitive: baseUi("Checkbox", "checkbox"),
    shadcn: "checkbox",
    examples: [{ file: "checkbox-demo", title: "Trạng thái và thẻ chọn" }],
    api: [{ name: "Checkbox", props: [{ name: "checked / defaultChecked / onCheckedChange", type: "boolean / (checked) => void", description: "Trạng thái chọn." }, { name: "indeterminate", type: "boolean", description: "Trạng thái chọn một phần (hiện dấu gạch)." }, primitiveRest("Checkbox.Root")] }],
  },
  {
    slug: "radio-group",
    name: "Radio Group",
    group: "Biểu mẫu",
    runtime: "island",
    description: "Nhóm chọn một. Nút tròn 18px, khi chọn viền tím với chấm tím 8px ở giữa — như Radio của FrameON.",
    imports: 'import { RadioGroup, RadioGroupItem } from "@hwagfu/frameui/radio-group"',
    primitive: baseUi("Radio Group", "radio"),
    shadcn: "radio-group",
    examples: [
      { file: "radio-group-demo", title: "Danh sách" },
      { file: "radio-group-cards", title: "Thẻ chọn gói", description: "Bọc `Field` trong `FieldLabel`: thẻ sáng viền vàng khi được chọn." },
    ],
    api: [
      { name: "RadioGroup", props: [{ name: "value / defaultValue / onValueChange", type: "…", description: "Giá trị đang chọn." }, primitiveRest("RadioGroup")] },
      { name: "RadioGroupItem", props: [{ name: "value", type: "string", description: "Giá trị của nút." }, primitiveRest("Radio.Root")] },
    ],
  },
  {
    slug: "switch",
    name: "Switch",
    group: "Biểu mẫu",
    runtime: "island",
    description: "Công tắc 40×22px của FrameON, bật thì rãnh tím và núm trắng trượt 18px.",
    imports: 'import { Switch } from "@hwagfu/frameui/switch"',
    primitive: baseUi("Switch", "switch"),
    shadcn: "switch",
    examples: [{ file: "switch-demo", title: "Trạng thái và kích thước" }],
    api: [{ name: "Switch", props: [{ name: "size", type: '"sm" | "default"', default: '"default"', description: "32×18 hoặc 40×22." }, { name: "checked / defaultChecked / onCheckedChange", type: "…", description: "Trạng thái bật." }, primitiveRest("Switch.Root")] }],
  },
  {
    slug: "slider",
    name: "Slider",
    group: "Biểu mẫu",
    runtime: "island",
    description: "Thanh kéo chọn giá trị hoặc khoảng. Rãnh trong mờ, đoạn đã chọn màu vàng như thanh tiến độ xem phim của FrameON.",
    imports: 'import { Slider } from "@hwagfu/frameui/slider"',
    primitive: baseUi("Slider", "slider"),
    shadcn: "slider",
    examples: [{ file: "slider-demo", title: "Một giá trị và khoảng" }],
    api: [{ name: "Slider", props: [{ name: "value / defaultValue", type: "number | number[]", description: "Mảng hai phần tử cho khoảng." }, { name: "min / max / step", type: "number", default: "0 / 100 / 1", description: "Giới hạn." }, primitiveRest("Slider.Root")] }],
  },
  {
    slug: "toggle",
    name: "Toggle",
    group: "Biểu mẫu",
    runtime: "island",
    description: "Nút bật/tắt. Khi bật: chữ vàng trên nền vàng 12%. Biến thể `outline` chính là Tag (chip lọc) của FrameON.",
    imports: 'import { Toggle } from "@hwagfu/frameui/toggle"',
    primitive: baseUi("Toggle", "toggle"),
    shadcn: "toggle",
    examples: [{ file: "toggle-demo", title: "Biểu tượng và chip lọc" }],
    api: [{ name: "Toggle", props: [{ name: "variant", type: '"default" | "outline"', default: '"default"', description: "`outline` = chip viên thuốc." }, { name: "size", type: '"sm" | "default" | "lg"', default: '"default"', description: "32 / 38 / 46px." }, { name: "pressed / defaultPressed / onPressedChange", type: "…", description: "Trạng thái bật." }] }],
  },
  {
    slug: "toggle-group",
    name: "Toggle Group",
    group: "Biểu mẫu",
    runtime: "client",
    description: "Nhóm toggle chọn một hoặc nhiều. `variant=\"outline\"` cho hàng chip lọc kho phim; `spacing={0}` ghép liền thành thanh.",
    imports: 'import { ToggleGroup, ToggleGroupItem } from "@hwagfu/frameui/toggle-group"',
    primitive: baseUi("Toggle Group", "toggle-group"),
    shadcn: "toggle-group",
    examples: [{ file: "toggle-group-demo", title: "Chip lọc và thanh căn lề" }],
    api: [{ name: "ToggleGroup", props: [{ name: "variant / size", type: "như Toggle", description: "Áp cho mọi item bên trong." }, { name: "spacing", type: "number", default: "2", description: "Khoảng cách (đơn vị spacing). 0 = ghép liền." }, { name: "multiple", type: "boolean", description: "Cho bật nhiều item." }, { name: "orientation", type: '"horizontal" | "vertical"', default: '"horizontal"', description: "Hướng xếp." }] }],
  },
  {
    slug: "field",
    name: "Field",
    group: "Biểu mẫu",
    runtime: "server",
    description:
      "Bộ khung biểu mẫu: nhãn, mô tả, lỗi, nhóm, fieldset. Thay cho các prop `label` / `hint` / `error` của Input/Select cũ trong FrameON. Lỗi hiển thị màu vàng như FrameON.",
    imports:
      'import { Field, FieldContent, FieldDescription, FieldError, FieldGroup, FieldLabel, FieldLegend, FieldSeparator, FieldSet, FieldTitle } from "@hwagfu/frameui/field"',
    shadcn: "field",
    examples: [{ file: "field-demo", title: "Biểu mẫu thanh toán" }],
    api: [
      { name: "Field", props: [{ name: "orientation", type: '"vertical" | "horizontal" | "responsive"', default: '"vertical"', description: "Bố cục nhãn và ô nhập." }, { name: "data-invalid / data-disabled", type: "boolean", description: "Đánh dấu trạng thái cho cả nhóm." }] },
      { name: "FieldError", props: [{ name: "errors", type: "Array<{ message?: string }>", description: "Danh sách lỗi (tương thích react-hook-form, TanStack Form…). Tự bỏ trùng." }] },
      { name: "FieldLegend", props: [{ name: "variant", type: '"legend" | "label"', default: '"legend"', description: "Cỡ tiêu đề của fieldset." }] },
    ],
  },
  {
    slug: "calendar",
    name: "Calendar",
    group: "Biểu mẫu",
    runtime: "client",
    description: "Lịch chọn ngày trên react-day-picker. Ô 36px, hôm nay chữ vàng, ngày chọn là chip vàng, khoảng ngày nền vàng nhạt.",
    imports: 'import { Calendar } from "@hwagfu/frameui/calendar"',
    shadcn: "calendar",
    uses: ["react-day-picker", "date-fns"],
    examples: [
      { file: "calendar-demo", title: "Chọn một ngày" },
      { file: "calendar-range", title: "Chọn khoảng ngày" },
    ],
    api: [{ name: "Calendar", props: [{ name: "mode", type: '"single" | "multiple" | "range"', description: "Kiểu chọn." }, { name: "buttonVariant", type: "ButtonVariant", default: '"ghost"', description: "Hình thức nút chuyển tháng." }, { name: "...props", type: "DayPickerProps", description: "Toàn bộ prop của react-day-picker." }] }],
  },
  {
    slug: "date-picker",
    name: "Date Picker",
    group: "Biểu mẫu",
    runtime: "client",
    description: "Công thức Date Picker của shadcn (Popover + Calendar) đóng gói thành component. Nút kích hoạt dùng bề mặt ô nhập FrameON.",
    imports: 'import { DatePicker, DateRangePicker } from "@hwagfu/frameui/date-picker"',
    shadcn: "date-picker",
    uses: ["react-day-picker", "date-fns"],
    examples: [{ file: "date-picker-demo", title: "Ngày và khoảng ngày (tiếng Việt)" }],
    api: [{ name: "DatePicker / DateRangePicker", props: [{ name: "value / defaultValue / onValueChange", type: "Date | DateRange", description: "Giá trị đã chọn." }, { name: "locale", type: "Locale", description: "Locale của date-fns, ví dụ `vi`." }, { name: "formatStr", type: "string", default: '"PPP"', description: "Mẫu định dạng date-fns cho nhãn." }, { name: "placeholder", type: "string", description: "Chữ khi chưa chọn." }, { name: "calendarProps", type: "CalendarProps", description: "Prop thêm cho Calendar bên trong." }] }],
  },
]
