import type { ComponentDoc } from "../types"
import { baseUi, classNameProp, primitiveRest, renderProp, restProp, sideProps } from "./shared"

export const navigation: ComponentDoc[] = [
  {
    slug: "breadcrumb",
    name: "Breadcrumb",
    group: "Điều hướng",
    runtime: "server",
    description: "Đường dẫn phân cấp. Liên kết xám, rê chuột chuyển vàng; trang hiện tại màu chữ chính.",
    imports: 'import { Breadcrumb, BreadcrumbEllipsis, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@hwagfu/frameui/breadcrumb"',
    shadcn: "breadcrumb",
    examples: [{ file: "breadcrumb-demo", title: "Đường dẫn phim" }],
    api: [{ name: "BreadcrumbLink", props: [renderProp, classNameProp, restProp("a")] }],
  },
  {
    slug: "pagination",
    name: "Pagination",
    group: "Điều hướng",
    runtime: "server",
    description: "Phân trang bằng liên kết thật — chạy hoàn toàn trên máy chủ qua searchParams. Trang hiện tại là chip vàng như Tag đang bật.",
    imports: 'import { Pagination, PaginationContent, PaginationEllipsis, PaginationItem, PaginationLink, PaginationNext, PaginationPrevious } from "@hwagfu/frameui/pagination"',
    shadcn: "pagination",
    examples: [{ file: "pagination-demo", title: "Phân trang" }],
    api: [
      { name: "PaginationLink", props: [{ name: "isActive", type: "boolean", description: "Trang hiện tại." }, { name: "size", type: "ButtonSize", default: '"icon"', description: "Cỡ nút." }, restProp("a")] },
      { name: "PaginationPrevious / PaginationNext", props: [{ name: "text", type: "string", default: '"Previous" / "Next"', description: "Nhãn (ẩn trên màn hình nhỏ)." }] },
    ],
  },
  {
    slug: "tabs",
    name: "Tabs",
    group: "Điều hướng",
    runtime: "island",
    description: "Các thẻ nội dung. `variant=\"line\"` là thanh tab của FrameON: đường kẻ mảnh bên dưới, tab đang chọn đậm, vàng, gạch chân vàng 2px. Mặc định là dạng phân đoạn.",
    imports: 'import { Tabs, TabsContent, TabsList, TabsTrigger } from "@hwagfu/frameui/tabs"',
    primitive: baseUi("Tabs", "tabs"),
    shadcn: "tabs",
    examples: [
      { file: "tabs-demo", title: "Thanh tab FrameON (line)" },
      { file: "tabs-segmented", title: "Phân đoạn (default)" },
    ],
    api: [
      { name: "Tabs", props: [{ name: "value / defaultValue / onValueChange", type: "any", description: "Tab đang chọn." }, { name: "orientation", type: '"horizontal" | "vertical"', default: '"horizontal"', description: "Hướng." }, primitiveRest("Tabs.Root")] },
      { name: "TabsList", props: [{ name: "variant", type: '"default" | "line"', default: '"default"', description: "`line` = thanh tab gạch chân của FrameON." }] },
    ],
    notes: ["Tab gắn với URL (đổi tab do máy chủ xử lý) thì dựng bằng các liên kết + `NavigationMenuLink` hoặc Pagination thay vì Tabs."],
  },
  {
    slug: "navigation-menu",
    name: "Navigation Menu",
    group: "Điều hướng",
    runtime: "island",
    description: "Thanh điều hướng chính như header FrameON: mục 16px, rê chuột hoặc đang mở thì vàng với gạch chân vàng; bảng con trên bề mặt lồng với nhãn nhóm in hoa.",
    imports: 'import { NavigationMenu, NavigationMenuContent, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger } from "@hwagfu/frameui/navigation-menu"',
    primitive: baseUi("Navigation Menu", "navigation-menu"),
    shadcn: "navigation-menu",
    examples: [{ file: "navigation-menu-demo", title: "Header kho phim" }],
    api: [
      { name: "NavigationMenu", props: [{ name: "align", type: '"start" | "center" | "end"', default: '"start"', description: "Căn bảng con." }, primitiveRest("NavigationMenu.Root")] },
      { name: "NavigationMenuLink", props: [{ name: "active", type: "boolean", description: "Trang hiện tại (thay cho NavLink `active` của FrameON)." }, primitiveRest("NavigationMenu.Link")] },
    ],
    notes: ["`navigationMenuTriggerStyle()` trả về class của mục menu để dùng cho liên kết tuỳ biến."],
  },
  {
    slug: "menubar",
    name: "Menubar",
    group: "Điều hướng",
    runtime: "island",
    description: "Thanh menu kiểu ứng dụng máy tính, dùng chung hàng menu với Dropdown Menu.",
    imports: 'import { Menubar, MenubarContent, MenubarItem, MenubarMenu, MenubarTrigger, … } from "@hwagfu/frameui/menubar"',
    primitive: baseUi("Menubar", "menubar"),
    shadcn: "menubar",
    examples: [{ file: "menubar-demo", title: "Menu trình phát" }],
  },
  {
    slug: "sidebar",
    name: "Sidebar",
    group: "Điều hướng",
    runtime: "island",
    description:
      "Thanh bên có thể thu gọn thành icon, tự thành Sheet trên di động, nhớ trạng thái bằng cookie, phím tắt ⌘B. Chỉ Provider, Sidebar, Trigger, Rail và MenuButton là client; mọi phần còn lại render trên máy chủ.",
    imports: 'import { Sidebar, SidebarContent, SidebarProvider, SidebarTrigger, … } from "@hwagfu/frameui/sidebar"',
    shadcn: "sidebar",
    examples: [{ file: "sidebar-demo", title: "Ứng dụng FrameON", description: "Bấm nút ở góc trên hoặc ⌘B để thu gọn thành icon.", iframe: 520 }],
    api: [
      { name: "SidebarProvider", props: [{ name: "defaultOpen / open / onOpenChange", type: "boolean", description: "Trạng thái mở." }] },
      { name: "Sidebar", props: [{ name: "side", type: '"left" | "right"', default: '"left"', description: "Phía." }, { name: "variant", type: '"sidebar" | "floating" | "inset"', default: '"sidebar"', description: "Kiểu hiển thị." }, { name: "collapsible", type: '"offcanvas" | "icon" | "none"', default: '"offcanvas"', description: "Cách thu gọn." }] },
      { name: "SidebarMenuButton", props: [{ name: "isActive", type: "boolean", description: "Mục hiện tại — đậm, vàng." }, { name: "tooltip", type: "string | TooltipContentProps", description: "Tooltip khi thu gọn." }, { name: "size", type: '"default" | "sm" | "lg"', default: '"default"', description: "36 / 32 / 48px." }, renderProp] },
      { name: "useSidebar()", props: [{ name: "state / open / setOpen / isMobile / toggleSidebar", type: "…", description: "Đọc và điều khiển sidebar từ Client Component." }] },
    ],
  },
  {
    slug: "dropdown-menu",
    name: "Dropdown Menu",
    group: "Điều hướng",
    runtime: "island",
    description: "Menu bật xuống của FrameON: nền trang, viền mảnh, bóng nổi; hàng cao 44px, rê chuột nền lồng + chữ vàng; dấu tick vàng cho mục đang chọn.",
    imports: 'import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger, … } from "@hwagfu/frameui/dropdown-menu"',
    primitive: baseUi("Menu", "menu"),
    shadcn: "dropdown-menu",
    examples: [
      { file: "dropdown-menu-demo", title: "Menu tài khoản" },
      { file: "dropdown-menu-checkboxes", title: "Chọn một và chọn nhiều" },
    ],
    api: [
      { name: "DropdownMenuContent", props: sideProps },
      { name: "DropdownMenuItem", props: [{ name: "variant", type: '"default" | "destructive"', default: '"default"', description: "`destructive` = chữ đỏ." }, { name: "inset", type: "boolean", description: "Thụt lề để thẳng hàng với mục có icon." }, primitiveRest("Menu.Item")] },
    ],
  },
  {
    slug: "context-menu",
    name: "Context Menu",
    group: "Điều hướng",
    runtime: "island",
    description: "Menu chuột phải, cùng hình thức với Dropdown Menu.",
    imports: 'import { ContextMenu, ContextMenuContent, ContextMenuItem, ContextMenuTrigger, … } from "@hwagfu/frameui/context-menu"',
    primitive: baseUi("Context Menu", "context-menu"),
    shadcn: "context-menu",
    examples: [{ file: "context-menu-demo", title: "Thao tác trên phim" }],
  },
  {
    slug: "command",
    name: "Command",
    group: "Điều hướng",
    runtime: "island",
    description: "Bảng lệnh/tìm nhanh trên cmdk. Mục đang chọn nền lồng + chữ vàng; nhãn nhóm in hoa nhỏ.",
    imports: 'import { Command, CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, … } from "@hwagfu/frameui/command"',
    shadcn: "command",
    uses: ["cmdk"],
    examples: [
      { file: "command-demo", title: "Bảng lệnh" },
      { file: "command-dialog-demo", title: "Trong hộp thoại (⌘J)" },
    ],
    api: [{ name: "CommandDialog", props: [{ name: "title / description", type: "string", description: "Tiêu đề cho trình đọc màn hình." }, { name: "showCloseButton", type: "boolean", default: "false", description: "Hiện nút đóng." }, { name: "open / onOpenChange", type: "…", description: "Như Dialog." }] }],
  },
]
