import type { ComponentDoc } from "../types"
import { baseUi, primitiveRest, sideProps } from "./shared"

export const overlays: ComponentDoc[] = [
  {
    slug: "dialog",
    name: "Dialog",
    group: "Lớp phủ",
    runtime: "island",
    description:
      "Hộp thoại phủ toàn màn hình: nền tối 50%, bảng `bg-modal` bo 12px rộng tối đa 600px, xuất hiện bằng hiệu ứng “pop” 180ms, tiêu đề 28px. `variant=\"promo\"` cho hộp mời VIP viền vàng phát sáng.",
    imports: 'import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@hwagfu/frameui/dialog"',
    primitive: baseUi("Dialog", "dialog"),
    shadcn: "dialog",
    examples: [
      { file: "dialog-demo", title: "Sửa hồ sơ" },
      { file: "dialog-promo", title: "Mời nâng cấp VIP (promo)" },
    ],
    api: [
      { name: "Dialog", props: [{ name: "open / defaultOpen / onOpenChange", type: "boolean", description: "Trạng thái mở (thay cho `open` + `onClose` của FrameON)." }, primitiveRest("Dialog.Root")] },
      { name: "DialogContent", props: [{ name: "variant", type: '"default" | "promo"', default: '"default"', description: "`promo` = viền vàng, gradient, tiêu đề vàng." }, { name: "showCloseButton", type: "boolean", default: "true", description: "Nút × ở góc." }, primitiveRest("Dialog.Popup")] },
      { name: "DialogFooter", props: [{ name: "showCloseButton", type: "boolean", default: "false", description: "Thêm nút “Close”." }] },
    ],
    notes: ["Nút mở dùng `DialogTrigger render={<Button />}` — tương đương prop `trigger` cũ của FrameON nhưng không phải clone phần tử."],
  },
  {
    slug: "alert-dialog",
    name: "Alert Dialog",
    group: "Lớp phủ",
    runtime: "island",
    description: "Hộp thoại xác nhận bắt buộc trả lời (không đóng khi bấm ra ngoài), cùng bề mặt với Dialog.",
    imports: 'import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, … } from "@hwagfu/frameui/alert-dialog"',
    primitive: baseUi("Alert Dialog", "alert-dialog"),
    shadcn: "alert-dialog",
    examples: [{ file: "alert-dialog-demo", title: "Xác nhận xoá" }],
    api: [
      { name: "AlertDialogContent", props: [{ name: "size", type: '"default" | "sm"', default: '"default"', description: "`sm` xếp hai nút thành lưới." }] },
      { name: "AlertDialogAction / AlertDialogCancel", props: [{ name: "variant / size", type: "như Button", description: "Cancel mặc định `secondary`." }] },
    ],
  },
  {
    slug: "sheet",
    name: "Sheet",
    group: "Lớp phủ",
    runtime: "island",
    description: "Bảng trượt từ mép màn hình — menu di động, bảng cài đặt.",
    imports: 'import { Sheet, SheetClose, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle, SheetTrigger } from "@hwagfu/frameui/sheet"',
    primitive: baseUi("Dialog", "dialog"),
    shadcn: "sheet",
    examples: [{ file: "sheet-demo", title: "Cài đặt trình phát" }],
    api: [{ name: "SheetContent", props: [{ name: "side", type: '"top" | "right" | "bottom" | "left"', default: '"right"', description: "Mép trượt vào." }, { name: "showCloseButton", type: "boolean", default: "true", description: "Nút × ở góc." }] }],
  },
  {
    slug: "drawer",
    name: "Drawer",
    group: "Lớp phủ",
    runtime: "client",
    description: "Ngăn kéo vuốt được (trên Base UI Drawer) với snap point, lồng nhau, tay nắm kéo.",
    imports: 'import { Drawer, DrawerClose, DrawerContent, DrawerDescription, DrawerFooter, DrawerHeader, DrawerTitle, DrawerTrigger } from "@hwagfu/frameui/drawer"',
    primitive: baseUi("Drawer", "drawer"),
    shadcn: "drawer",
    examples: [{ file: "drawer-demo", title: "Chọn tập" }],
    api: [{ name: "Drawer", props: [{ name: "swipeDirection", type: '"down" | "up" | "left" | "right"', default: '"down"', description: "Hướng vuốt để đóng." }, { name: "showSwipeHandle", type: "boolean", default: "false", description: "Hiện tay nắm." }, { name: "snapPoints", type: "Array<number | string>", description: "Các điểm dừng." }, primitiveRest("Drawer.Root")] }],
  },
  {
    slug: "popover",
    name: "Popover",
    group: "Lớp phủ",
    runtime: "island",
    description: "Bảng nổi neo vào phần tử — như bảng thông báo trên header FrameON (bề mặt lồng, bóng nổi, hiệu ứng pop).",
    imports: 'import { Popover, PopoverContent, PopoverDescription, PopoverHeader, PopoverTitle, PopoverTrigger } from "@hwagfu/frameui/popover"',
    primitive: baseUi("Popover", "popover"),
    shadcn: "popover",
    examples: [{ file: "popover-demo", title: "Thông báo" }],
    api: [{ name: "PopoverContent", props: sideProps }],
  },
  {
    slug: "hover-card",
    name: "Hover Card",
    group: "Lớp phủ",
    runtime: "island",
    description: "Thẻ xem trước khi rê chuột lên liên kết.",
    imports: 'import { HoverCard, HoverCardContent, HoverCardTrigger } from "@hwagfu/frameui/hover-card"',
    primitive: baseUi("Preview Card", "preview-card"),
    shadcn: "hover-card",
    examples: [{ file: "hover-card-demo", title: "Xem trước phim" }],
    api: [{ name: "HoverCardContent", props: sideProps }],
  },
  {
    slug: "tooltip",
    name: "Tooltip",
    group: "Lớp phủ",
    runtime: "island",
    description: "Chú thích nhỏ khi trỏ chuột hoặc focus: bề mặt modal, chữ 12px, cách phần tử 8px, không mũi tên — như Tooltip của FrameON, nhưng tự lật khi chạm mép và không bị khung cha cắt.",
    imports: 'import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@hwagfu/frameui/tooltip"',
    primitive: baseUi("Tooltip", "tooltip"),
    shadcn: "tooltip",
    examples: [{ file: "tooltip-demo", title: "Nút biểu tượng" }],
    api: [
      { name: "TooltipProvider", props: [{ name: "delay", type: "number", default: "0", description: "Độ trễ (ms) trước khi hiện." }] },
      { name: "TooltipContent", props: sideProps },
    ],
  },
]
