// Generates src/lib/icons.tsx from lucide-react's icon data (ISC licence).
// The generated components are plain SVG with no hooks and no "use client",
// so they render as static HTML inside Server Components.
import { writeFileSync, realpathSync } from "node:fs"
import { pathToFileURL } from "node:url"
import { join } from "node:path"

const ICONS = {
  CheckIcon: "check",
  ChevronDownIcon: "chevron-down",
  ChevronUpIcon: "chevron-up",
  ChevronLeftIcon: "chevron-left",
  ChevronRightIcon: "chevron-right",
  XIcon: "x",
  Loader2Icon: "loader-circle",
  TriangleAlertIcon: "triangle-alert",
  OctagonXIcon: "octagon-x",
  MoreHorizontalIcon: "ellipsis",
  InfoIcon: "info",
  CircleCheckIcon: "circle-check",
  CircleAlertIcon: "circle-alert",
  CircleXIcon: "circle-x",
  SearchIcon: "search",
  PanelLeftIcon: "panel-left",
  MinusIcon: "minus",
  ArrowDownIcon: "arrow-down",
  GripVerticalIcon: "grip-vertical",
  ArrowUpIcon: "arrow-up",
  ChevronsUpDownIcon: "chevrons-up-down",
  ChevronsLeftIcon: "chevrons-left",
  ChevronsRightIcon: "chevrons-right",
  EyeOffIcon: "eye-off",
  Settings2Icon: "settings-2",
  CalendarIcon: "calendar",
}

const dir = join(realpathSync("node_modules/lucide-react"), "dist/esm/icons")
const out = []
for (const [name, file] of Object.entries(ICONS)) {
  const { __iconData } = await import(pathToFileURL(join(dir, `${file}.mjs`)).href)
  const node = __iconData.node
  const clean = node.map(([tag, attrs]) => {
    const { key, ...rest } = attrs
    return [tag, rest]
  })
  out.push(`export const ${name} = createIcon("${file}", ${JSON.stringify(clean)})`)
}

const header = `// Generated by scripts/gen-icons.mjs — do not edit by hand.
// Icon paths come from Lucide (https://lucide.dev, ISC licence).
import { createIcon } from "./create-icon"

`
writeFileSync("src/lib/icons.tsx", header + out.join("\n") + "\n")
console.log(`wrote ${out.length} icons`)
