// Generated by scripts/gen-examples.mjs — do not edit by hand.
import type { ComponentType } from "react"

import AccordionDemo from "./accordion-demo"
import AlertDemo from "./alert-demo"
import AlertDialogDemo from "./alert-dialog-demo"
import AspectRatioDemo from "./aspect-ratio-demo"
import AttachmentDemo from "./attachment-demo"
import AvatarDemo from "./avatar-demo"
import BadgeDemo from "./badge-demo"
import BreadcrumbDemo from "./breadcrumb-demo"
import BubbleDemo from "./bubble-demo"
import ButtonDemo from "./button-demo"
import ButtonGroupDemo from "./button-group-demo"
import ButtonLink from "./button-link"
import ButtonSizes from "./button-sizes"
import CalendarDemo from "./calendar-demo"
import CalendarRange from "./calendar-range"
import CardDemo from "./card-demo"
import CardVariants from "./card-variants"
import CarouselDemo from "./carousel-demo"
import ChartArea from "./chart-area"
import ChartDemo from "./chart-demo"
import CheckboxDemo from "./checkbox-demo"
import CollapsibleDemo from "./collapsible-demo"
import ComboboxDemo from "./combobox-demo"
import ComboboxMultiple from "./combobox-multiple"
import CommandDemo from "./command-demo"
import CommandDialogDemo from "./command-dialog-demo"
import ContextMenuDemo from "./context-menu-demo"
import DataTableDemo from "./data-table-demo"
import DatePickerDemo from "./date-picker-demo"
import DialogDemo from "./dialog-demo"
import DialogPromo from "./dialog-promo"
import DirectionDemo from "./direction-demo"
import DrawerDemo from "./drawer-demo"
import DropdownMenuCheckboxes from "./dropdown-menu-checkboxes"
import DropdownMenuDemo from "./dropdown-menu-demo"
import EmptyDemo from "./empty-demo"
import FieldDemo from "./field-demo"
import FilmPeekDemo from "./film-peek-demo"
import HoverCardDemo from "./hover-card-demo"
import InputDemo from "./input-demo"
import InputField from "./input-field"
import InputGroupDemo from "./input-group-demo"
import InputOtpDemo from "./input-otp-demo"
import ItemDemo from "./item-demo"
import KbdDemo from "./kbd-demo"
import KbdModifiers from "./kbd-modifiers"
import LabelDemo from "./label-demo"
import LogoDemo from "./logo-demo"
import LogoFramex from "./logo-framex"
import LogoFramexEffects from "./logo-framex-effects"
import LogoIntroDemo from "./logo-intro-demo"
import LogoMotion from "./logo-motion"
import LogoSoundFrameon from "./logo-sound-frameon"
import LogoSoundFramex from "./logo-sound-framex"
import LogoSoundHover from "./logo-sound-hover"
import MarkerDemo from "./marker-demo"
import MediaChipDemo from "./media-chip-demo"
import MenubarDemo from "./menubar-demo"
import MessageDemo from "./message-demo"
import MessageScrollerDemo from "./message-scroller-demo"
import NativeSelectDemo from "./native-select-demo"
import NavigationMenuDemo from "./navigation-menu-demo"
import PaginationDemo from "./pagination-demo"
import PopoverDemo from "./popover-demo"
import PosterArtDemo from "./poster-art-demo"
import PosterCardDemo from "./poster-card-demo"
import PosterCardTop10 from "./poster-card-top10"
import PosterCardWide from "./poster-card-wide"
import ProgressDemo from "./progress-demo"
import QuestionnaireDemo from "./questionnaire-demo"
import RadioGroupCards from "./radio-group-cards"
import RadioGroupDemo from "./radio-group-demo"
import RankListDemo from "./rank-list-demo"
import ResizableDemo from "./resizable-demo"
import ScrollAreaDemo from "./scroll-area-demo"
import SelectDemo from "./select-demo"
import SeparatorDemo from "./separator-demo"
import SheetDemo from "./sheet-demo"
import SidebarDemo from "./sidebar-demo"
import SkeletonDemo from "./skeleton-demo"
import SliderDemo from "./slider-demo"
import SonnerDemo from "./sonner-demo"
import SpinnerDemo from "./spinner-demo"
import SwitchDemo from "./switch-demo"
import TableDemo from "./table-demo"
import TabsDemo from "./tabs-demo"
import TabsSegmented from "./tabs-segmented"
import TextareaDemo from "./textarea-demo"
import ToastDemo from "./toast-demo"
import ToggleDemo from "./toggle-demo"
import ToggleGroupDemo from "./toggle-group-demo"
import TooltipDemo from "./tooltip-demo"
import TypographyDemo from "./typography-demo"

export const examples: Record<string, ComponentType> = {
  "accordion-demo": AccordionDemo,
  "alert-demo": AlertDemo,
  "alert-dialog-demo": AlertDialogDemo,
  "aspect-ratio-demo": AspectRatioDemo,
  "attachment-demo": AttachmentDemo,
  "avatar-demo": AvatarDemo,
  "badge-demo": BadgeDemo,
  "breadcrumb-demo": BreadcrumbDemo,
  "bubble-demo": BubbleDemo,
  "button-demo": ButtonDemo,
  "button-group-demo": ButtonGroupDemo,
  "button-link": ButtonLink,
  "button-sizes": ButtonSizes,
  "calendar-demo": CalendarDemo,
  "calendar-range": CalendarRange,
  "card-demo": CardDemo,
  "card-variants": CardVariants,
  "carousel-demo": CarouselDemo,
  "chart-area": ChartArea,
  "chart-demo": ChartDemo,
  "checkbox-demo": CheckboxDemo,
  "collapsible-demo": CollapsibleDemo,
  "combobox-demo": ComboboxDemo,
  "combobox-multiple": ComboboxMultiple,
  "command-demo": CommandDemo,
  "command-dialog-demo": CommandDialogDemo,
  "context-menu-demo": ContextMenuDemo,
  "data-table-demo": DataTableDemo,
  "date-picker-demo": DatePickerDemo,
  "dialog-demo": DialogDemo,
  "dialog-promo": DialogPromo,
  "direction-demo": DirectionDemo,
  "drawer-demo": DrawerDemo,
  "dropdown-menu-checkboxes": DropdownMenuCheckboxes,
  "dropdown-menu-demo": DropdownMenuDemo,
  "empty-demo": EmptyDemo,
  "field-demo": FieldDemo,
  "film-peek-demo": FilmPeekDemo,
  "hover-card-demo": HoverCardDemo,
  "input-demo": InputDemo,
  "input-field": InputField,
  "input-group-demo": InputGroupDemo,
  "input-otp-demo": InputOtpDemo,
  "item-demo": ItemDemo,
  "kbd-demo": KbdDemo,
  "kbd-modifiers": KbdModifiers,
  "label-demo": LabelDemo,
  "logo-demo": LogoDemo,
  "logo-framex": LogoFramex,
  "logo-framex-effects": LogoFramexEffects,
  "logo-intro-demo": LogoIntroDemo,
  "logo-motion": LogoMotion,
  "logo-sound-frameon": LogoSoundFrameon,
  "logo-sound-framex": LogoSoundFramex,
  "logo-sound-hover": LogoSoundHover,
  "marker-demo": MarkerDemo,
  "media-chip-demo": MediaChipDemo,
  "menubar-demo": MenubarDemo,
  "message-demo": MessageDemo,
  "message-scroller-demo": MessageScrollerDemo,
  "native-select-demo": NativeSelectDemo,
  "navigation-menu-demo": NavigationMenuDemo,
  "pagination-demo": PaginationDemo,
  "popover-demo": PopoverDemo,
  "poster-art-demo": PosterArtDemo,
  "poster-card-demo": PosterCardDemo,
  "poster-card-top10": PosterCardTop10,
  "poster-card-wide": PosterCardWide,
  "progress-demo": ProgressDemo,
  "questionnaire-demo": QuestionnaireDemo,
  "radio-group-cards": RadioGroupCards,
  "radio-group-demo": RadioGroupDemo,
  "rank-list-demo": RankListDemo,
  "resizable-demo": ResizableDemo,
  "scroll-area-demo": ScrollAreaDemo,
  "select-demo": SelectDemo,
  "separator-demo": SeparatorDemo,
  "sheet-demo": SheetDemo,
  "sidebar-demo": SidebarDemo,
  "skeleton-demo": SkeletonDemo,
  "slider-demo": SliderDemo,
  "sonner-demo": SonnerDemo,
  "spinner-demo": SpinnerDemo,
  "switch-demo": SwitchDemo,
  "table-demo": TableDemo,
  "tabs-demo": TabsDemo,
  "tabs-segmented": TabsSegmented,
  "textarea-demo": TextareaDemo,
  "toast-demo": ToastDemo,
  "toggle-demo": ToggleDemo,
  "toggle-group-demo": ToggleGroupDemo,
  "tooltip-demo": TooltipDemo,
  "typography-demo": TypographyDemo,
}
